export default [
    {
        ver:1,
        stores:{
            userInfo:[
                'id',
                'name'
            ],
            todoList:[
                'id',
                'status',
                'title',
                'date',
                'dueDate',
                'subList',
                'remark',
                'star',
                'commits',
                'filterId'
            ],
            subTodoList:[
                'id',
                'status',
                'title',
                'pId'
            ],
            filters:[
                'id',
                'title'
            ]
        }
    }
]